'use client';

import { Icon } from '@/components/ui/Icon';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card } from '@/components/ui/Card';
import { Pill } from '@/components/ui/Pill';

export default function SEOPage() {
  const tools = [
    { icon: 'title', label: 'Meta tags', desc: 'Per-page meta titles and descriptions managed via Next.js Metadata API.', status: 'Active' },
    { icon: 'robot_2', label: 'Robots & Sitemap', desc: 'robots.txt and sitemap.xml generated by Next.js at build time.', status: 'Active' },
    { icon: 'image', label: 'Open Graph', desc: 'OG images and social sharing metadata configured per product page.', status: 'Active' },
    { icon: 'analytics', label: 'Search console', desc: 'Connect Google Search Console for indexing insights.', status: 'Planned' },
    { icon: 'speed', label: 'Core Web Vitals', desc: 'Monitor page speed, LCP, CLS, and INP scores.', status: 'Planned' },
    { icon: 'schema', label: 'Structured data', desc: 'JSON-LD product schema for rich search results.', status: 'Planned' },
  ];

  return (
    <div className="anim-fade-in flex flex-col gap-[24px]">
      <PageHeader
        eyebrow="Storefront"
        title="SEO"
        subtitle="Optimize your storefront for search engines and discoverability."
      />

      {/* Current Setup Info */}
      <Card>
        <div className="flex items-start gap-[16px]">
          <div className="w-[44px] h-[44px] rounded-[11px] bg-[var(--sage-soft)] text-[var(--sage)] flex items-center justify-center shrink-0">
            <Icon name="check_circle" size={22} />
          </div>
          <div>
            <div className="text-[14.5px] font-medium text-[var(--ink)] mb-[6px]">Next.js SEO Active</div>
            <p className="m-0 text-[13px] text-[var(--ink-2)] leading-[1.6]">
              Your storefront uses the <strong>Next.js Metadata API</strong> for SEO management. Meta titles, descriptions, and OG tags are configured directly in your page components and layouts.
              The admin panel is excluded from search indexing via <code className="text-[12px] py-[1px] px-[5px] bg-[var(--bg-sunk)] rounded-[4px] font-mono">X-Robots-Tag: noindex</code> headers.
            </p>
          </div>
        </div>
      </Card>

      <div className="grid grid-cols-[repeat(auto-fill,minmax(280px,1fr))] gap-[16px]">
        {tools.map((t) => (
          <Card key={t.label}>
            <div className="flex items-start justify-between mb-[14px]">
              <div className={`w-[44px] h-[44px] rounded-[11px] flex items-center justify-center ${t.status === 'Active' ? 'bg-[var(--sage-soft)] text-[var(--sage)]' : 'bg-[var(--saffron-soft)] text-[var(--saffron-ink)]'}`}>
                <Icon name={t.icon} size={22} />
              </div>
              <Pill tone={t.status === 'Active' ? 'sage' : 'saffron'} size="sm">{t.status}</Pill>
            </div>
            <div className="text-[14.5px] font-medium text-[var(--ink)] mb-[6px]">{t.label}</div>
            <p className="m-0 text-[13px] text-[var(--ink-2)] leading-[1.5]">{t.desc}</p>
          </Card>
        ))}
      </div>

      {/* Product SEO reminder */}
      <Card>
        <div className="flex items-center gap-[12px] mb-[12px]">
          <Icon name="lightbulb" size={20} className="text-[var(--saffron)]" />
          <div className="text-[13.5px] font-medium text-[var(--ink)]">Per-product SEO</div>
        </div>
        <p className="m-0 text-[13px] text-[var(--ink-2)] leading-[1.6]">
          Each product has its own <strong>Meta Title</strong> and <strong>Meta Description</strong> fields on the product edit page.
          Navigate to <strong>Products → Edit</strong> to configure SEO metadata for individual products.
          A visual admin UI for global SEO settings will ship in a future release.
        </p>
      </Card>
    </div>
  );
}
