'use client';

import { Icon } from '@/components/ui/Icon';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card, cardStyle } from '@/components/ui/Card';
import { Pill } from '@/components/ui/Pill';
import type { CSSProperties } from 'react';

export default function SEOPage() {
  const tools = [
    { icon: 'title', label: 'Meta tags', desc: 'Per-page meta titles and descriptions managed via Next.js Metadata API.', status: 'Active' },
    { icon: 'robot_2', label: 'Robots & Sitemap', desc: 'robots.txt and sitemap.xml generated by Next.js at build time.', status: 'Active' },
    { icon: 'image', label: 'Open Graph', desc: 'OG images and social sharing metadata configured per product page.', status: 'Active' },
    { icon: 'analytics', label: 'Search console', desc: 'Connect Google Search Console for indexing insights.', status: 'Planned' },
    { icon: 'speed', label: 'Core Web Vitals', desc: 'Monitor page speed, LCP, CLS, and INP scores.', status: 'Planned' },
    { icon: 'schema', label: 'Structured data', desc: 'JSON-LD product schema for rich search results.', status: 'Planned' },
  ];

  return (
    <div className="anim-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      <PageHeader
        eyebrow="Storefront"
        title="SEO"
        subtitle="Optimize your storefront for search engines and discoverability."
      />

      {/* Current Setup Info */}
      <Card>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: 16 }}>
          <div style={{
            width: 44, height: 44, borderRadius: 11,
            background: 'var(--sage-soft)', color: 'var(--sage)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            flexShrink: 0,
          }}>
            <Icon name="check_circle" size={22} />
          </div>
          <div>
            <div style={{ fontSize: 14.5, fontWeight: 500, color: 'var(--ink)', marginBottom: 6 }}>Next.js SEO Active</div>
            <p style={{ margin: 0, fontSize: 13, color: 'var(--ink-2)', lineHeight: 1.6 }}>
              Your storefront uses the <strong>Next.js Metadata API</strong> for SEO management. Meta titles, descriptions, and OG tags are configured directly in your page components and layouts.
              The admin panel is excluded from search indexing via <code style={{ fontSize: 12, padding: '1px 5px', background: 'var(--bg-sunk)', borderRadius: 4, fontFamily: 'var(--font-mono)' }}>X-Robots-Tag: noindex</code> headers.
            </p>
          </div>
        </div>
      </Card>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 16 }}>
        {tools.map((t) => (
          <Card key={t.label}>
            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 14 }}>
              <div style={{
                width: 44, height: 44, borderRadius: 11,
                background: t.status === 'Active' ? 'var(--sage-soft)' : 'var(--saffron-soft)',
                color: t.status === 'Active' ? 'var(--sage)' : 'var(--saffron-ink)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                <Icon name={t.icon} size={22} />
              </div>
              <Pill tone={t.status === 'Active' ? 'sage' : 'saffron'} size="sm">{t.status}</Pill>
            </div>
            <div style={{ fontSize: 14.5, fontWeight: 500, color: 'var(--ink)', marginBottom: 6 }}>{t.label}</div>
            <p style={{ margin: 0, fontSize: 13, color: 'var(--ink-2)', lineHeight: 1.5 }}>{t.desc}</p>
          </Card>
        ))}
      </div>

      {/* Product SEO reminder */}
      <Card>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
          <Icon name="lightbulb" size={20} style={{ color: 'var(--saffron)' }} />
          <div style={{ fontSize: 13.5, fontWeight: 500, color: 'var(--ink)' }}>Per-product SEO</div>
        </div>
        <p style={{ margin: 0, fontSize: 13, color: 'var(--ink-2)', lineHeight: 1.6 }}>
          Each product has its own <strong>Meta Title</strong> and <strong>Meta Description</strong> fields on the product edit page.
          Navigate to <strong>Products → Edit</strong> to configure SEO metadata for individual products.
          A visual admin UI for global SEO settings will ship in a future release.
        </p>
      </Card>
    </div>
  );
}
